### ISSUE TITLE
Dopamine ignores .opus files

### ISSUE THREAD

**Issue by Nord-Licht** [digimezzo/dopamine-windows#1095]
## I'm submitting a...
<pre><code>
[X ] Regression 
[ ] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions
* Windows version: Windows 10 Pro, Ver. 1909, Build 18363.592
* Dopamine version: 2.0, 2.0.1

## Reproduction steps
* Install Dopamine 2.0.1 or 2.0
* Add directory with Opus Files

## Observed behavior
The Database stays empty, Dopamine (2.0, 2.0.1) completly ignores the files. The problem does not occur with Ver. 1.5. There the behavior is like intended. I will attach the logs from 2.0 and 1.5.

## Log file
[Dopamine_1.5.log](https://github.com/digimezzo/dopamine-windows/files/4075819/Dopamine_1.5.log)
[Dopamine_2.0.log](https://github.com/digimezzo/dopamine-windows/files/4075820/Dopamine_2.0.log)

**Comment by Erithax** [comment]
This issue was closed, I believe because it was thought to have been fixed, but I'm running into this exact issue on a clean install of dopamine on Windows 10 where there are multiple directories with hundreds of .opus files which aren't showing up anywhere while the couple .m4a's in those directories are showing up.

**Comment by digimezzo** [comment]
@TheOnlyRealCoder The issue is fixed for the upcoming 2.0.2 release. I haven't had a chance to finalize that release though. I'll try to speed things up.
