### ISSUE TITLE
Cannot properly sort by track number in an album with multiple artists

### ISSUE THREAD

**Issue by dgrenzo** [digimezzo/dopamine-windows#1165]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report  
[x] Feature request
</code></pre>

In compilation albums, the "By Album" sort option sorts alphabetically by Artist before Track Number. When each track is by a different artist this effectively sorts the album alphabetically by artist. I'm not sure if this should be a change to how the By Album sort is applied or a new sort option should be added. It looks like the default in EntityUtils.OrderTracksAsync would do it.

**Comment by digimezzo** [comment]
@dgrenzo Thank you for reporting this! That sorting is, indeed, wrong. i will correct it for the next version.
Many thanks for looking at the code and pointing out where the issue lies.

**Comment by digimezzo** [comment]
@dgrenzo After review, it seems that the sorting is correct after all. Dopamine first sorts by album artist, then by albumtitle. An album is defined by these 2 tags. Of course, for all tracks in an album, the album artist must be the same (otherwise they are not part of the same album. For compilation albums, the album artist must be the same for all tracks. That is the only way to group tracks into 1 album. You can choose something like "Various artists".
