### ISSUE TITLE
Merge the same music files in the playlist

### ISSUE THREAD

**Issue by gjhwssg** [digimezzo/dopamine-windows#131]
**If add subfolders, the same music files in the playlist.**
![image](https://cloud.githubusercontent.com/assets/4454357/18190163/1e3d5b7a-70f3-11e6-9f0b-97bef950c2ad.png)

**Play file**
![image](https://cloud.githubusercontent.com/assets/4454357/18190263/e822fd96-70f3-11e6-9c93-4bac425da5df.png)

**Comment by digimezzo** [comment]
Could you check the path of duplicate songs? Is it the same?

**Comment by gjhwssg** [comment]
Yes,the file just in subfoler.

**Comment by digimezzo** [comment]
That's strange. I can't reproduce it here. Dopamine should ignore files for which there is already a same path in the "Tracks" table. Could you send me your Dopamine.db file? I suspect it might have something to do with renaming of folders from uppercase to lowercase or inverse. Because I know Dopamine considers e.g; these 2 paths as different:

c:\Music\Test
c:\Music\test

I should compare by lowercasing or uppercasing the paths.

**Comment by gjhwssg** [comment]
I can not find your email.
Post here.
Dopamine.db
[Dopamine.zip](https://github.com/digimezzo/Dopamine/files/451633/Dopamine.zip)

![image](https://cloud.githubusercontent.com/assets/4454357/18199283/36241ff0-7132-11e6-9476-bfda8056ff8a.png)

![image](https://cloud.githubusercontent.com/assets/4454357/18199286/3cc79b70-7132-11e6-8dd0-ba2c8ca586a2.png)

![image](https://cloud.githubusercontent.com/assets/4454357/18199292/46684008-7132-11e6-8969-31306fe9d9f7.png)

![image](https://cloud.githubusercontent.com/assets/4454357/18199309/4e5b3338-7132-11e6-9b41-bec09ba12afe.png)

**Comment by digimezzo** [comment]
I was able to reproduce this today. It is important to follow this order:

- In Windows, create a folder anywhere, the create a sub folder in that folder. Add an audio file to the sub folder
- In Dopamine, make sure there are no collection folders and that the collection is empty
- Add the main folder and the sub folder as collection folders to Dopamine
- Refresh the collection => the audio file is added twice
