### ISSUE TITLE
suggestion: narrower interface

### ISSUE THREAD

**Issue by mah-qurashy** [digimezzo/dopamine-windows#145]
i understand that controls need to be widely spaced for touch usability, but there seem to be too much white space in top and bottom panels that is taking much of the screen's real estate that should be available for content, especially for lower res screens
here is a concept that i made that saves around 44 pixels compared to the current layout
![dop2](https://cloud.githubusercontent.com/assets/20822445/18298586/005d5cb6-74ba-11e6-9c4a-c79603433e40.jpg)
![dop1](https://cloud.githubusercontent.com/assets/20822445/18298587/0077ff1c-74ba-11e6-904d-887332275bac.jpg)

**Comment by Khidreal** [comment]
not only controls need an update in my opinion. recently I sent my concept art of a better interface to the developer, through email. speaking of touch screens, even all that information on the menus aligned to left is hard to click using a touch screen. in my case, I joined artists, genres and albums under the same tab and centered this menus to fill more white space. during the development of my concept, I also thought about making not only controls, but menus too a bit smaller to fit inside smaller screens, but than, just supposition, it will look really small on bigger screens. imagine having a 27'' screen... it can only work, if Dopamine is adaptive to the resolution, meaning: it's interface goes bigger or smaller depending on the screen resolution. don't know if it does this already, but since you made this suggestion, I think not. so the way to go, in my honest and personal opinion, would be making Dopamine adapt to any screen resolution, make it have a dynamic size instead of a fixed size.

**Comment by mah-qurashy** [comment]
windows does automatically scale up all applications on very high dpi screens using its dpi setting
the only thing a developer would do about scaling is to add multiple bitmap sources for each dpi so they would still look sharp
i am using 24" 1080 panel on a desktop and a 15.6 HD touchscreen convertible
on the desktop dopamine feels fine but on the lower resolution screen space becomes much more valuable that the top and bottom bars are taking 30% or so of the application height (calculated)
groove for example has a similar problem but bottom bar is smaller and its color and transparency relieve the feel about the wasted  space

**Comment by digimezzo** [comment]
Dopamine is designed and developed on a laptop which has a screen resolution of 1600x900. It work quite right on that resolution which, I believe, is quite low.

Further, Dopamine uses vector graphics for icons, which are sharp at different scaling factors. Cached album art was designed and tested to work at desktop scaling ranging from 100% to 150%. 

Some white space is required in applications. In the above concepts, top element have too little vertical white space, which gives an impression of clutter. For the bottom, it could be acceptable. But the added value is so little, that it makes little sense to implement. Some arguments against the bottom part: the cover art becomes smaller, there is less room to add other elements (like rating), the spectrum analyzer comes closer to the playback control buttons.

The concept that I was sent by e-mail (where the sub menu is centered, and the main menu remains left aligned) breaks the design that I have in mind for this player. In the future, more elements will be added to the sub menu, e.g. "Files", which will allows viewing a folder structure like it is on your disk. So it will take more space than it is now.

Don't fear white space like that. It is required to keep an overview an keep user friendliness of your UI.

**Comment by mah-qurashy** [comment]
i would never prefer space taken from content for a spectrum analyzer anyway
it's not much about the actual added value but its about how the user perceives it
i mean look at this, this is just painful to look at, it feels like i could easily add six more tracks or so (even though i probably couldn't)
![untitled-3](https://cloud.githubusercontent.com/assets/20822445/18413997/899a0d46-77ba-11e6-8cf0-a788101c7fd8.jpg)

**Comment by digimezzo** [comment]
Agreed about the songs screen. The "Columns" button wastes a lot of space. Would it make sense to put it in the right-click menu?

About the bottom part. I'll give it a shot to make it narrower. It actually looks quite good on your concept.
