### ISSUE TITLE
in mini player, the album art shadow overlays the progress bar button

### ISSUE THREAD

**Issue by mah-qurashy** [digimezzo/dopamine-windows#181]
![untitled-2](https://cloud.githubusercontent.com/assets/20822445/19535103/c5935f96-9646-11e6-9e2b-f9415512e5a6.png)

**Comment by bwat47** [comment]
I noticed this as well. only seems to effect the light theme so switching to the dark theme work as a workaround

**Comment by digimezzo** [comment]
Indeed, it's the black color of the progress handle that causes this. The only solutions I see for now:
1. Add a subtle white gradient at the bottom of the cover art so the progress handle becomes more visible on dark cover art
2. Use the accent color on the progress handle instead of black (in the case above, it would be blue)
