### ISSUE TITLE
Same Location Installation Causing Uninstallation

### ISSUE THREAD

**Issue by Riajyuu** [digimezzo/dopamine-windows#258]
Existing in 1.2 braches
STR:
1. Install Dopamine 1.2
2. When choose location for installing updates, no matter from your website .msi or application update delivery, select the same folder with previous version.
3. wait until finish.
Actual Result: Dopamine is actually uninstalled.

**Comment by digimezzo** [comment]
That's already fixed in c3e931300385c2aca566c0411fda1c1a4a9becf0. That commit is in the new release 1.2.1.

 If you installed version 1.2, and you then install 1.2.1, the installation will still uninstall Dopamine. However, from the next version on it'll work fine.

People upgrading from builds  which are older than 1.2 build 845, to 1.2.1, will not have the issue anymore.
