### ISSUE TITLE
Collection - "Folder" Section

### ISSUE THREAD

**Issue by basis7net** [digimezzo/dopamine-windows#484]
Next to the "Artists - Genres - Albums - Songs - Playlists - Frequent" Sections a "Folder"-Section would be amazing to selectivly crawl through Folders. 

So far I Love Dopamine!! (What's about an Android Version?)

**Comment by digimezzo** [comment]
~~Thanks for loving Dopamine. And Android version is planned. As for the folder option. That has already been requested multiple times, and will  probably not happen. I feel I'd be re-creating some kind of Windows explorer. That's not Dopamine's responsibility.~~

**Comment by digimezzo** [comment]
I changed my mind on this one. I'm getting a lot of requests for such a feature, so I'm adding it to version 2.0.

If anyone has examples on how they would like this to be implemented (or examples in an existing media player), please post them here. All ideas are welcome.

**Comment by huntardy** [comment]
In AIMP Music Library if you choose no grouping on the hamburger the left panel shows a file folder structure rather than a genre or artist but it looks rather dull.  Perhaps using the same UI layout from your playlist section only replacing the left hand panel with a directory tree and keeping the visual elements to the right with song list centre.

**Comment by digimezzo** [comment]
This feature is now implemented and will be available in Dopamine 2.0 Preview 2.
