### ISSUE TITLE
V1.4 Build 952 Blank icon on the taskbar

### ISSUE THREAD

**Issue by kayasax** [digimezzo/dopamine-windows#509]
Hi first of all thank you for this nice player 👍 
I've just installed the preview versionand noticed a very small issue the icon is blank on the taskbar : 
![2017-10-04 09 40 07](https://user-images.githubusercontent.com/1241767/31164736-af074a98-a8e8-11e7-89c8-87e93c6c6732.png)

**Comment by digimezzo** [comment]
Hi! Thanks for liking it.
The icon thing is a known issue. It is because Dopamine gets uninstalled and re-installed when installing a new build. That's the safest way to make sure the user has all files in the correct place. Because of the uninstall, the pinned icon on the taskbar gets lost. The workaround is  to unpin and pin it again. This issue is related to #293.

**Comment by kayasax** [comment]
yep this resolved the thing. Thanks a lot
