### ISSUE TITLE
How can I join the translation project?

### ISSUE THREAD

**Issue by TragicLifeHu** [digimezzo/dopamine-windows#602]
##  Issues
I wanted to join the Translation,but I just have no permission to do it.
I turly love this application and I want to do something for it.
I am a native Chinese speaker.I have joined many Translation Projects.

Here is my translation

##  **Translation**
For Simplified Chinese (简体中文)
Based on Version 1.5.5
```
  <Text Key="Enable_System_Notification">启用系统通知（仅限 Windows 10）</Text>
  <Text Key="Show_Song_Covers">显示曲目封面</Text>
  <Text Key="Hide_Song_Covers">隐藏曲目封面</Text>
  <Text Key="Check_For_Updates_At_Startup">在启动时检查更新</Text>
  <Text Key="Check_For_Updates_Periodically">定期检查更新</Text>
  <Text Key="Refresh_Collection_Now">立即刷新音乐库</Text>
  <Text Key="Album_Covers">专辑封面</Text>
  <Text Key="Reload_All_Covers">重新更新所有封面</Text>
  <Text Key="Reload_All_Covers_Description">为所有专辑更新封面，即使有的已经有了封面。</Text>
  <Text Key="Reload_Missing_Covers">重新更新缺失封面</Text>
  <Text Key="Reload_Missing_Covers_Description">只为没有封面的专辑更新封面</Text>
  <Text Key="Added_Songs">已添加 {number} 首曲目 ({percent}%)</Text>
  <Text Key="Download_Missing_Album_Covers">从网络下载所有缺失的专辑封面</Text>
  <Text Key="Also_Enqueue_Other_Files_In_Folder">当从 Windows 资源管理器播放音频文件时，还会加入同一文件夹中的其他音频文件。</Text>
```

**Comment by KrayZeee** [comment]
fork, push changes to fork, send pull request

**Comment by FixxeS** [comment]
or more easy: you can just go on the computer,
C:\PROGRAM FILES (X86)\DOPAMINE\LANGUAGES
grab the english file, it's a simple xml file that you can right click and open with Notepad (I recommend using something like Notepad++ or Atom, Brackets or anything because it's easier to read) and translate it. than you can just send the file to the email or facebook account of Digimezzo.
much easier than going on forking and stuff, since everything is reviewed anyway by Digimezzo, you are just adding work to yourself and losing your time forking the project and making pull requests.

or at least that's how I used to do it, like, a year ago or something... I just came back from linux, and the player improved a lot!

**Comment by KrayZeee** [comment]
@FixxeS while this is easy for things like ONE xml file, it is flawed in a few ways.
1. its annoying, to have to gather code from different sources, (github, mail, facebook...) its overhead of work which can be avoided by just using the frigging tools github is providing u..

do you know that u dont even have to clone the repo to your local machine if you dont want to... just press the fork button, in your profile go to the repo and the file you want to edit, press the edit button, change the file to your like and save it, some explanation in the commit box highly recommended, after that you just  press the "new pullrequest" button and "create pullrequest". easy isnt it?

2. if you want to be part of something you should be able to play by the rules of the group. basicly learn git. 

3. changes made by the community isnt often as easy as a single xml file. many git repos are using continous integration, basicly after someone pushes something an automated system tests it if it compiles and other things. which is not provided if you send code by facebook.. waah getting goosebumps

so instead of making yourself the least work, try to be considerate and dont make the devs all the work for you

**Comment by TragicLifeHu** [comment]
All Finished! Thanks for HLP
