### ISSUE TITLE
Low quality album cover in 4k display 250% scaling 

### ISSUE THREAD

**Issue by HaloTechnology** [digimezzo/dopamine-windows#610]
![capture](https://user-images.githubusercontent.com/25601934/34323880-bf396a74-e829-11e7-8b80-81731d20054b.PNG)
You can see from the screenshot even though the Text is super crisp the album cover are not .

Bare in mind that I do have 1500x1500 Embedded covers in the files .

Music bee rendered correctly but lags because of the high quality rendering

**Comment by digimezzo** [comment]
Some background info for developers:

Instead of linking to the full cover images, Dopamine generates thumbnails of album covers, to improve the album list's performance. The default thumbnail sizes are defined by:

```
public static double CoverSmallSize = 120;
public static double CoverMediumSize = 150;
public static double CoverLargeSize = 180;
```
So, when a thumbnail of 120px is created, and a Windows desktop scaling > 100% is used, images appear blurry, because Windows stretches the 120px image to fit a "virtual" 120px spot (essentially 120*desktop scaling factor). To avoid blur, Dopamine upscales thumbnails by 1.5 by default:

`public static readonly double CoverUpscaleFactor = 1.5;`

That resolves blur for scaling up to 150%. So it is expected that for 250%, blur still occurs.

**Ideal solution**

Ideally, we should detect the Windows scaling factor, and modify the upscale factor accordingly. From some investigation and testing, that seems to be an impossible task. Also, since Windows 10, it is possible to us a different scaling per monitor. That makes the task even harder.

**Practical solution 1**

Increase CoverUpscaleFactor to 2.5 by default. That will fix blur until 250% scaling. That could however decrease album list performance and it overkill for those that don't use such high resolution images and scaling factor.

**Practical solution 2**

Keep a CoverUpscaleFactor of 1.5 by default, but provide a toggle in the settings, which allows using a CoverUpscaleFactor of 2.5 for those with higher resolution monitors.
