### ISSUE TITLE
Feature: Adding Folder Tree as an option for organizing the music library

### ISSUE THREAD

**Issue by Vik279** [digimezzo/dopamine-windows#679]
Hi! I love the player, but me and probably other users too, organize their library with folders. It would be really useful to add this feature! I attach an image of how this could look. Thank you!

![folder tree suggestion](https://user-images.githubusercontent.com/37021105/36935999-74336ffe-1eff-11e8-91df-a1065045d6a4.jpg)

**Comment by PhillyMay** [comment]
Would also love to see the integration of a folder tab.

Organizing music within folders instead of playlists allow for better cross plattform operability. For example my music is stored on Onedrive. My whole Collection gets automatically downloaded to my phone via the "OneSync". A lot of cool Players like "Retro Music", "Shutle Music" or "Pulsar" show me my music folders, so I can simply tap on such a directory and start my shuffle playback.  There's no need for an import/export of .m3u files (a process you could not automate) and you are save from problems that result from apps that don't handle these files properly.

**Comment by Dons35** [comment]
I would also really appreciate this feature being added. I can't use Dopamine because it doesn't allow sorting by folders (many of my songs have messed up metadata, or missing because ripped from a cd, etc), and I would really love to because everything else about it is the best.

**Comment by digimezzo** [comment]
This feature has been added to Dopamine 2.0. You can test it out in the latest preview.
