### ISSUE TITLE
[Feature Request] Convert Media to 320kbps AAC Version

### ISSUE THREAD

**Issue by raaomoka** [digimezzo/dopamine-windows#699]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report  
[x] Feature request
</code></pre>

Hi,

I was just recently referred to Dopamine by another user, so, I downloaded the portable application and I'm already loving it! Love that it's a portable application with a very great UI and support for editing metadata, automatically grabbing album art from the internet, adding lyrics, love the Playback UI that follows album color and allows displaying of Lyrics, love that it can integrate with the Windows built-in headsup media notification (albeit no album art), love how it automatically grabs artist info from the web, etc.

However, it doesn't seem to support creating 320kbps AAC files and other formats, similar to iTunes. I've been building my media library in this now widely supported media format, and it generally achieves better sound quality than mp3 at similar bit rates. Would greatly appreciate it if this your awesome application implemented support for converting audio files to this 320kbps AAC file format, and possibly other media file formats.

Thanks in advance.

**Comment by KrayZeee** [comment]
#652 No

**Comment by raaomoka** [comment]
Well, I'll just stick with iTunes if that's the case. Already have Groove for merely playing Music...just want an all-in-one tool for organizing my media library without the iTunes bloat and sluggish UI.

**Comment by digimezzo** [comment]
Dopamine exists because a lot of players have chosen to become all in one solutions, and that is exactly what we're trying to avoid here. There are currently no plans to add audio trans-coding to Dopamine.

Additionally, converting existing audio files to AAC won't give you better quality. It will depend on the source format. If the source format is lossless, you'll have a good quality AAC. If the source format if lossy, you'll make the quality even worse after conversion.
