### ISSUE TITLE
Can I get dopamine from the Microsoft store?

### ISSUE THREAD

**Issue by ghost** [digimezzo/dopamine-windows#705]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report  
[x] Feature request
</code></pre>

Dopamine is a great music player and I love it. I hope to get it from the Microsoft store.
Microsoft Store can directly install software, instead of going to the website to download the installation package and then manually install it and can automatically upgrade my software.
Finally, thanks to the author for the creation of dopamine.

**Comment by xxKeith20xx** [comment]
FWIW: Dopamine auto updates

**Comment by ghost** [comment]
I know that dopamine can be updated automatically, but it still needs to go to the website to download the installation package and then install it.
Microsoft Store makes it easy to get and update software.

**Comment by digimezzo** [comment]
Are you using the Portable version? If not, the installable version downloads the package automatically, and notifies you when it is ready to install. One click on the notification bar, starts the installation.

As for the Microsoft Store: I currently have no plans to add Dopamine to the Store. The migration to the store is a tedious process, which I started a few months ago, but abandoned. It wasn't fun. 

I'm trying to keep a balance between the effort required for deployment (my effort) and the effort required to install (the user's effort). The current updater does a good job at providing this balance (unless it is broken, in which case you should notify me). The store would add an extra layer of complexity and manual work that I don't want right now. The project must remain fun for the developer too, otherwise the project is doomed to die.

**Comment by ghost** [comment]
You did not adopt my opinion, but thank you for developing such a great player.
