### ISSUE TITLE
Crashes When Refreshing Library

### ISSUE THREAD

**Issue by lukewarmandbothered** [digimezzo/dopamine-windows#732]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ X] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

Windows version: Windows 10, Version 10.0.16299 Build 16299
Dopamine version: 1.5.13

## Reproduction steps

Step 1 Open app
Step 2 Add folder for library

## Observed behavior
Collection refreshes automatically and crashes at 5% every time.

## Desired behavior
Dopamine should create library.
[Dopamine.log](https://github.com/digimezzo/Dopamine/files/1936316/Dopamine.log)

**Comment by lukewarmandbothered** [comment]
Note: this is the first time I'm using this app on this PC. I was able to add a few random, smaller folders to the library successfully. This also happens with the previous build (1.5.12.0).

Other steps I've tried:
* Disabled anti-virus
* Made library folder not read-only
* Installed latest Windows Updates

**Comment by lukewarmandbothered** [comment]
So, I narrowed it down to one particular album, and the mp3 files specifically. If I added any of them to the collection, even one by one, it would cause the crash. I could not tell anything from the files that differentiated them, unfortunately.

**Comment by digimezzo** [comment]
Could you send me one of those files that cause the crash? I'd like to try to at least prevent Dopamine from crashing when encountering such files.
Thanks!

**Comment by lukewarmandbothered** [comment]
Sure, here's the smallest one. Confirmed it causes the crash. Let me know if I can be of any more assistance. Thanks!

[08 - The Three Shadows Part 3.zip](https://github.com/digimezzo/Dopamine/files/1939790/08.-.The.Three.Shadows.Part.3.zip)

**Comment by RobH99** [comment]
It is a bad file header it seems, even though the music part of the file is probably alright.
MP3val states >

'Wrong number of MPEG frames specified in Xing header (0 instead of 3710)'

MP3val also corrected the file fine, so maybe you could try that program on your files and then try to get Dopamine to re-catalogue them.  (Try on a copy or backup of the files first!)  

MP3Val can look at single files or whole albums, or even in bulk if the whole list is manageable.  I ran it to check my files in batches of about 20 albums at a time.

I have had this problem on just a few mp3's out of tens of thousands, but MP3val fixed them all.  It is a great little program even though it only appears in beta apparently (version 0.1.8 is the latest).

Also, look at the comments field inside the mp3 file and maybe change it; it has some strange characters in there> ', AG# 10DC3EC1'

**Comment by RobH99** [comment]
UPDATE:

I tried with your original file and Dopamine (not version 1.5.14) does indeed crash.
After I fixed the mp3 file in MP3val, Dopamine was fine and it added it perfectly, so that was the problem.  I also noticed that MP3Val makes a backup of the original file automatically, which is good.

The original file would probably play in some other mp3 players because they handle the file header differently and are maybe not too bothered about it.  This could maybe lead to other problems further down the line however.  In my view, the best thing to do is fix the mp3's.

It appears that the rubbish in the comments field inside the mp3 does not affect anything, but it is strange, and maybe just needs deleting unless you want to use it.

**Comment by digimezzo** [comment]
@RobH99 It's indeed caused by corrupt MP3 headers. TagLib# (the tag reading library we're using) has a bug where it causes a crash when calculating Bitrate and Duration when the headers are corrupt. I forked the TagLib#project, patched it and could fix the issue. If the fix appear stable, I'll create a pull request for TagLib#. 

With this fix, TagLib#, and thus Dopamine, react more like other players. The corrupt headers don't cause a crash. However, it causes problems down the line, like you predicted. In the case of this track, the duration is wrong. At least Foobar2000 reports the same, incorrect, duration as Dopamine. So I'm satisfied. Correcting the MP3 file is the best option.

**Comment by RobH99** [comment]
Excellent!  Thanks for the extra information.  

You are doing superb work with Dopamine with all of these tweaks and improvements.
The player is already far better and easier to use than most of the others out there.
I just know that version 2 will be something special.

**Comment by lukewarmandbothered** [comment]
Excellent work, guys! I scanned and reparied with mp3val and that did the trick. This is a great app!
