### ISSUE TITLE
Order album tracks "By Album" wrong

### ISSUE THREAD

**Issue by Bearlify** [digimezzo/dopamine-windows#885]
Trackers are ordered as follows:

01
10
02

**Comment by franktopel** [comment]
I'm having this issue as well:

![grafik](https://user-images.githubusercontent.com/10668603/47613548-71d99c80-da91-11e8-816b-35999c9e9b12.png)

The order of the songs is visually wrong, even though they are played in the correct order.

![grafik](https://user-images.githubusercontent.com/10668603/47613557-b2391a80-da91-11e8-80b1-51cb0de43839.png)

This is the case for whatever album I checked.

![grafik](https://user-images.githubusercontent.com/10668603/47613602-bb76b700-da92-11e8-8717-27877fa835d8.png)

**Comment by digimezzo** [comment]
~~Is this on preview 2?~~

~~Could you upload your Dopamine.db file somewhere so I can reproduce the issue here? I currently cannot reproduce it, and the ordering is ok here. You'll find Dopamine.db in folder %appdata%\Dopamine~~

Nevermind this question. I found an album on my computer, which also has this issue.

**Comment by franktopel** [comment]
Donated 15,00 € to show my apppreciation of what you do.

**Comment by digimezzo** [comment]
@franktopel Thank you very much! :)
