### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by kbalint** [digimezzo/dopamine-windows#98]
Dopamine usually eats up ~250-400MB of memory (Win10 x64, 12GB RAM, i5-4690), but last time it was ~700MB when I restarted. I have a solid ~40GB music library, and usually play it randomly from the tray (no gui updates needed). iTunes only using at about ~100-200MB with the same library (1.1 build 672).

**Comment by digimezzo** [comment]
The 700 MB memory usage, is that just after starting Dopamine?

**Comment by kbalint** [comment]
no, after 6-8 hours of continuous play

**Comment by kbalint** [comment]
after reloading my library several times (fixing the mp3 tags for artists / albums) it's now 1122.9MB, so there's a memory leak somewhere

**Comment by digimezzo** [comment]
How do you reload the library? By pressing "Refresh"? (Just trying to find out how to best reproduce this)

**Comment by kbalint** [comment]
Settings -> Collection -> Refresh now

**Comment by kbalint** [comment]
plus changing between albums costs ~150-200 MB: https://www.youtube.com/watch?v=_KTNiBovFUs

**Comment by digimezzo** [comment]
Thanks for the extra info. I plan to tackle performance issues in version 1.2. See #100.

**Comment by Khidreal** [comment]
I tried to run this issues on my computer, since I only have 4GB ram, ram it's a precious thing here, equal to a diamond :)
so, i tried to reproduce it, and I couldn't. I think it may be a problem with your computer, because here I did this:
put dopamine playing a playlist, was consuming about 48-52MB ram. after 1h came back. the ram usage 
was basically the same, ranging from 49-52MB.
also the video you made, I tried to reproduce it too. it indeed makes dopamine use more ram, but on my computer after 10 seconds, it reduced to ~50MB. same for reloading the library. made dopamine use an extra 10MB and than reduced to 50 again after some seconds. so I think it's due to your hyper mega big collection, it's more data to be handled, so it demands more fuel (ram) and I think that is your problem. my setup is an i5 2.6GHz, SSD 240GB + windows 8.1 and only 18songs ('cause I use soundcloud). remember that OS's handle programs differently. at least was what a guy once said on the microsoft community. try using a smaller library, may help, because I also reduced my library from 18 songs to 1, restarted dopamine and I noticed it was using less 20MB of ram.

**Comment by kbalint** [comment]
>  try using a smaller library, may help, because I also reduced my library from 18 songs to 1

kidding, right? my ipod from 2003 could handle 15GB of music in one library

**Comment by Khidreal** [comment]
> kidding, right? my ipod from 2003 could handle 15GB of music in one library

we, the geeks on my school (I was the one that designed the interface), turned a desktop computer into basically an Ipod or MP3 player with screen. it was an old computer (more than 10 years) located on the library of my school that was even lagging on using google chrome. we put it with 4GB ram instead of 1 and now the school radio has it, it's like a super computer to play songs... does not lagg, works like a charm, making that old windows XP use only 200MB ram (yeah, as much as a music player)... it was our best and successful project we ever had LOL.
so as you see, the services and programs running in background have a huge impact on the performance. so you can't compare a thing that does 1 job against a thing that does 1 million. you can have a super computer with 4 i7's, 200GB of ram and 4 or 5 SSD disks inside, the old 2003 Ipod will always be better.

**Comment by digimezzo** [comment]
Let's keep this issue constructive folks. Memory usage in Dopamine is caused by multiple things:
1. The way .NET allocates memory for it's applications: it's more than for native applications. When running Dopamine on 64 bit systems, the memory cost will be even higher than when running the same code on a 32 bit system, just because the way .NET allocates memory. In Windows Task manager, you are not seeing how much memory is used by the .NET application, only how much the memory manager has allocated.
2. There is something going on when switching artists, albums,... The memory goes up. It goes down a bit after some time, when the .NET garbage collector fires up. But it never drops to its original value. That's strange, and I'll look into it.

@kbalint, how is memory usage since version 1.1? As I've done already quite some changes to how tracks are loaded in memory, reducing the number of objects which needed storage in memory.

**Comment by kbalint** [comment]
Gents, I checked it again with 1.2 (728), and it is still there: if you load up some albums, and click between the covers in full view (as shown in the video) it is still eating up memory at a rate of ~10Mb / album selection. I wonder if it is a WPF issue? The longer the tracklist for an album, the worst.

**Comment by digimezzo** [comment]
@kbalint Thanks for checking it out. I can see the same behavior here, although not as pronounced (my collection is much smaller). I don't know yet what causes it. I'll do more tests, replacing different components of the albums list.

**Comment by digimezzo** [comment]
@kbalint I found at least 1 source of memory leak. The little spectrum animation in the list of songs when a song is playing, is causing memory to leak when switching artists, genre, and probably other stuff. When I remove that animation, the memory doesn't go so high anymore, and drops better when the garbage collector kicks in. I'll now try to find out why that animation causes that issue.

**Comment by digimezzo** [comment]
The leak is fixed. For the developers among us. It was a DependencyPropertyDescriptor event handler that wasn't unhooked once the [SpectrumAnimation](https://github.com/digimezzo/Dopamine/blob/7cdc426d964a37b7ac6a84cbd85687ded791d2a0/Dopamine.Common/Controls/SpectrumAnimation.cs#L10) was unloaded. Because each song in the songs list contains such SpectrumAnimation, when changing the content of the list, the items didn't get disposed due to that event handler. That caused the memory leak.
