### ISSUE TITLE
Dopamine closes immediately after starting (Caused by MSI Afterburner / Rivatuner)

### ISSUE THREAD

**Issue by CntrlAltDel45** [digimezzo/dopamine-windows#984]
After the Windows 10 1903 feature update Dopamine does not work, the latest preview version 2 even the older 1.5 version does the exact same thing. 
When you launch Dopamine it closes immediately. Tried reinstalling Windows 10 but the issue persists.

**Comment by digimezzo** [comment]
Could you attach the log file?

**Comment by CntrlAltDel45** [comment]
[Dopamine.log](https://github.com/digimezzo/Dopamine/files/3268913/Dopamine.log)

**Comment by berkeleynerd** [comment]
Latest version working for me on 1903 so doesn't seem to be a problem for everyone at least.

**Comment by CntrlAltDel45** [comment]
Do you have any suggestions as to what I could possibly do to fix the issue? Dopamine is quite literally the best music player on the Windows platform, I'd hate to have to switch back to WMP.

**Comment by digimezzo** [comment]
Could you delete Settings.xml (it is in directory %appdata%\Dopamine. I want to make  sure that the settings file didn't get corrupt. It will be re-created next time you start dopamine.

**Comment by CntrlAltDel45** [comment]
@digimezzo Alright I just tried that and it does the same thing. Did fresh install afterwards and same thing on initial launch. Below is the fresh Dopamine log after first launch immediately crashes.

[Dopamine.log](https://github.com/digimezzo/Dopamine/files/3269877/Dopamine.log)

**Comment by CntrlAltDel45** [comment]
Same symptoms as in this issue report: https://github.com/digimezzo/Dopamine/issues/958

**Comment by digimezzo** [comment]
The log is, unfortunately not helpful. Dopamine seems to stop, without logging anything. In case of #958 things were different. A NullReferenceException was logged due to a bug in the code.

Could you have a look in the Windows Event Viewer > Application log, if there are any notifications concerning application crashes around the time that Dopamine gets closed? If you are not familiar with Event viewer, I can give you some more instructions. Let me know. 

I'll also try it today on a Windows 1903. Hopefully I'm getting the problem too.

**Comment by CntrlAltDel45** [comment]
I've attached a screenshot on the event viewer logged event relating to Dopamine crashing
![2019-06-10 12_40_52-Window](https://user-images.githubusercontent.com/51515349/59190438-04403380-8b7d-11e9-8eb4-98e71d57b489.png)

**Comment by CntrlAltDel45** [comment]
@digimezzo Alright, I managed to fix the issue. After seeing the faulting module path in the event viewer (d3d9.dll) I did some research and found out that it's MSI Afterburner conflicting with Dopamine, once you close MSI Afterburner package (specifically Rivatuner statistics) Dopamine launches seamlessly.

[UPDATE]
I managed to fix the issue by manually installing a later version of d3d9.dll in system32 which utilizes x86 d3d9.dll modules and in Syswow64 (which is not necessary) with latest x64 d3d9.dll modules. Specifically release 10.0.17763.1 for both x86 and x64 modules.

I can now run both Afterburner suite (with Rivatuner) and Dopamine without getting crashes on startup in Dopamine.

Thank you all for your assistance. If you need any more information please dont hesitate to write to me.

**Comment by digimezzo** [comment]
@CntrlAltDel45 That is very useful info. Thanks! I did some quick research and this doesn't seem to be limited to Dopamine. Other applications can suffer from this too. There seems to be a way to add exceptions to RivaTuner, hwoever I'm not familiar with it, so I'm not sure it is 100% corrent. This is the link I found: https://www.reddit.com/r/Windows10/comments/64tsw2/some_apps_are_crashing_with_msi_afterburner_rtss/

I'm glad your issue is now resolved! :)

**Comment by CntrlAltDel45** [comment]
@digimezzo That is correct. The issue has nothing to do with Dopamine and almost exclusively to do with newer d3d9.dll binaries. The same thing happened with the initial launch of the creator's update. I see this issue extends to all programs which utilizes the d3d9.dll binaries specifically the 32 bit variation in system32.

Discord, older games, hardware accelerated game launchers and some other Windows store apps are rendered useless since they cant launch. I've decided to go back to RS5 and leave 19H1 for when it's ready.

**Comment by madmax2** [comment]
@CntrlAltDel45 can you share the link for the d3d9.dll you got?
i got issue with dopamine not opening
